FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build-env
COPY ./DSFiles_Shared /DSFiles_Shared


WORKDIR /DSFiles-Server

# Copy only necessary files
COPY . ./

# Restore as distinct layers
RUN dotnet restore --no-cache

# Build and publish a release, skipping restore
RUN dotnet publish -c Release -o out --no-restore



# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0


WORKDIR /DSFiles-Server


RUN apt-get update \
 && apt-get install -y --no-install-recommends curl gnupg2 ca-certificates \
 && curl -sSL -O https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb \
 && dpkg -i packages-microsoft-prod.deb \
 && rm packages-microsoft-prod.deb \
 && apt-get update \
 && apt-get install -y --no-install-recommends libmsquic \
 && rm -rf /var/lib/apt/lists/*


# Copy only published output,
COPY --from=build-env /DSFiles-Server/out .

# Remove unnecessary runtimes (e.g., Windows, macOS)
RUN rm -rf ./runtimes/win* ./runtimes/osx* ./runtimes/unix*

# Set environment variables to reduce image size
ENV ASPNETCORE_URLS=http://+:8080 \
    DOTNET_EnableDiagnostics=0

# Expose the port
EXPOSE 8080

ENTRYPOINT ["dotnet", "DSFiles_Server.dll"]
